workflows:
  native-ios:
    name: BitChat Native iOS Build
    environment:
      xcode: latest
    scripts:
      - name: Install CocoaPods
        script: |
          cd ios
          pod install || echo "No Podfile"
      - name: Build archive
        script: |
          xcodebuild clean -project BitChat.xcodeproj -scheme BitChat -configuration Release
          xcodebuild archive \
            -project BitChat.xcodeproj \
            -scheme BitChat \
            -archivePath $CM_BUILD_DIR/BitChat.xcarchive \
            -sdk iphoneos \
            -configuration Release
      - name: Export .ipa
        script: |
          xcodebuild -exportArchive \
            -archivePath $CM_BUILD_DIR/BitChat.xcarchive \
            -exportOptionsPlist exportOptions.plist \
            -exportPath $CM_BUILD_DIR/ipa
    artifacts:
      - ipa/*.ipa
