workflows:
  native-ios:
    name: BitChat Native iOS Build
    environment:
      xcode: latest
    scripts:
      - name: Build archive
        script: |
          xcodebuild clean \
            -project bitchat.xcodeproj \
            -scheme bitchat \
            -configuration Release

          xcodebuild archive \
            -project bitchat.xcodeproj \
            -scheme bitchat \
            -archivePath $CM_BUILD_DIR/bitchat.xcarchive \
            -sdk iphoneos \
            -configuration Release
      - name: Export .ipa
        script: |
          xcodebuild -exportArchive \
            -archivePath $CM_BUILD_DIR/bitchat.xcarchive \
            -exportOptionsPlist exportOptions.plist \
            -exportPath $CM_BUILD_DIR/ipa
    artifacts:
      - ipa/*.ipa
